### ISSUE TITLE
reconciliation loops runs three times on charm upgrade

### ISSUE THREAD

**Issue by mthaddon** [canonical/wordpress-k8s-operator#145]
### Bug Description

The reconciliation loop runs three times on charm upgrade. See https://pastebin.canonical.com/p/3CJxW9mB4m/ for an example (sorry, Canonical internal only).

### To Reproduce

1. Deploy wordpress according to the docs
2. Trigger a charm upgrade
3. Observe the following two entries in the logs:
```
Start reconciliation process, triggered by <ConfigChangedEvent via WordpressCharm/on/config_changed[6]>
Start reconciliation process, triggered by <PebbleReadyEvent via WordpressCharm/on/apache_prometheus_exporter_pebble_ready[16]>
Start reconciliation process, triggered by <PebbleReadyEvent via WordpressCharm/on/wordpress_pebble_ready[21]>
```

### Environment

Juju 2.9.44 on OpenStack, but should be reproducible on any environment

### Relevant log output

```shell
See above
```

### Additional context

N/A

**Comment by weiiwang01** [comment]
I believe this is the expected behavior for WordPress. The reconciliation process for WordPress is designed to be lightweight, checking before making any modifications. This ensures updates are applied only when necessary, so each reconciliation shouldn't consume more resources than a typical web request. This design ensures that the WordPress charm remains stateless for simplicity.

**Comment by cbartz** [comment]
Closed due explanatory comment https://github.com/canonical/wordpress-k8s-operator/issues/145#issuecomment-1765722052 .
